### ISSUE TITLE
Add support for uploading videos to google+

### ISSUE THREAD

**Issue by CptanPanic** [vinitkumar/googlecl#242]
I think this is similar to picassa, but do not know.  Any chance of adding support for uploading videos to google+?
Thanks.

**Comment by 7specialgems** [comment]
This story may benefit from a change of name.

Google+ was discontinued on August 1st 2015 in favour of Google Photos.

It appears Google Photos uses the previous Picasa Web Albums API and supports video:

https://developers.google.com/picasa-web/docs/1.0/developers_guide_protocol?hl=en#PostVideo

**Comment by vinitkumar** [comment]
@CptanPanic Google+ is being closed, so I won't attempt to do anything in this regard. Closing this issue.
