### ISSUE TITLE
Add Gmail features

### ISSUE THREAD

**Issue by dav-s** [vinitkumar/googlecl#244]
With the [new Gmail api](https://developers.google.com/gmail/) released, it might not be too hard to implement Gmail as a service.

Sending an email could be similar to using `post` with the Blogger service, except the user would specify a recipient.

Getting emails would be a `list`, I suppose.

**Comment by vinitkumar** [comment]
@dav-s Will look into the possibility of this during the rewrite. Maybe in the later versions when a solid alpha version of it works. Closing it in favour of #274 to keep things clean. But making a note for this in #274 as well
