### ISSUE TITLE
Does it support the new OAuth 2 protocol?

### ISSUE THREAD

**Issue by Konstantinusz** [vinitkumar/googlecl#251]

**Comment by Konstantinusz** [comment]
Does it support the new OAuth 2 protocol?

**Comment by vinitkumar** [comment]
@Konstantinusz I already have a feature request to implement it but I haven't found much time last week. I am planning to implement it this week. 

Cheers!

**Comment by mesmariusz** [comment]
Any news ?

**Comment by vinitkumar** [comment]
@mesmariusz Sorry, I have been really caught up with work, Didn't got much time to look into it. I will try and get this done this week.

**Comment by gevrey** [comment]
@vinitkumar Thanks a lot mate, we appreciate your time.

**Comment by hrpunio** [comment]
Just for reference: OAuth2 as implemented with  https://github.com/google/oauth2client works here:
https://github.com/leocrawford/picasawebsync

**Comment by vinitkumar** [comment]
@hrpunio Thanks for the reference. This really helps.

**Comment by megavenik** [comment]
Hi, @vinitkumar!
How is the OAuth2 implementation going?:)

**Comment by vinitkumar** [comment]
Hi @megavenik I was having really busy time at work so it was getting delayed. But now, I think this week I can have it ready.

**Comment by mesmariusz** [comment]
Temporary solution: 

http://pinkaccordions.blogspot.com/2015/06/wysyanie-plikow-na-picasaweb-za-pomoca.html

But it would be nice to see googlecl working again :-)

**Comment by megavenik** [comment]
@mesmariusz @vinitkumar yeah! I've got a bunch of code already based on googlecl - it will be perfect, if we can use googlecl again)

**Comment by vinitkumar** [comment]
@mesmariusz @megavenik Guys, I am really sorry for the delay but I really want to make sure you guys can use the full googlecl with Oauth2 again.

**Comment by 7specialgems** [comment]
Any news?

**Comment by gevrey** [comment]
Dear @vinitkumar, do you have some time to look into this issue by any chance?
Many thanks.

**Comment by vinitkumar** [comment]
@all: I am having really busy time at work so wasn't able to give it proper time. But now I would take out my personal time to get this done. Sorry for inconvenience.

**Comment by vinitkumar** [comment]
Guys, I had a chance to look into implementing Oauth2 for https://github.com/vinitkumar/googlecl/. 
The implementation is in works now. I can't give an ETA right now as I am still busy planning and reading some part of the code. I might have to remove some services if they are not available with latest Google APIs. I will for sure some new services. 

I will try to maintain backward compatibility but can't promise anything at this moment. Also, I am sorry for being late to looking into this. My daily work didn't really allowed me much time for investing time into it. But now, I have decided to invest more time into it. 
 
Cheers!
/cc @gevrey @7specialgems @megavenik @mesmariusz @Konstantinusz

**Comment by gevrey** [comment]
Thank you @vinitkumar for your dedication.
Looking forward to see the new version. 
Do your best.
Christophe

**Comment by jorisrobijn** [comment]
Thank you so much for your efforts, it's great you keep googlecl this alive!
Would it be possible to release a version with only still-working services, so no new services yet?

**Comment by vinitkumar** [comment]
@jorisrobijn Yes, that's my plan. I will first try to get the still-working services out and then will think about getting more services. I will keep you guys posted about the progress. Expect something to test pretty soon.

**Comment by gevrey** [comment]
Hi @vinitkumar, any update by chance?
Thanks!

**Comment by mesmariusz** [comment]
I don't think so... Looks googleCL is dead.

But hopefully (based on my own investigation) there are other quite nice solutions:

1). http://megatools.megous.com/ (50 GB for free, Linux CLI available)
2). http://xmodulo.com/access-dropbox-command-line-linux.html (only 2GB but you can increase up to 16 GB for free: https://db.tt/n9rcXeSZ )

Dropbox has got excellent auto galery creation solution (during pictures upload). I use it for my home monitoring storage ;-)

Best regards
Mariusz

**Comment by vinitkumar** [comment]
@mesmariusz GoogleCL isn't dead but more because I have been neck deep in my work. Would love to have someone share the coding if possible. Else, I will do it on my own as soon as I find time.

**Comment by gevrey** [comment]
@vinitkumar Happy to help with the coding.

**Comment by vinitkumar** [comment]
@gevrey Thanks. Let's have a conversation about it on weekend?

**Comment by ics-brettma** [comment]
I would have to agree with suggestions that this port of GoogleCL is dead because @vinitkumar is unable to commit time to it and is the only supporter of the port.

@mesmariusz Thank you for linking to some live alternative solutions.

**Comment by gevrey** [comment]
@vinitkumar Sure. I am in Paris time zone. Add @pobox.com to my user name to mail me.

**Comment by gevrey** [comment]
@ics-brettma Why not volunteering? Just asking...

**Comment by ics-brettma** [comment]
@gevrey Lack of Python expertise at this time. My full appreciation goes out to everyone who is able to revive this tool.

**Comment by gevrey** [comment]
My expertise is mostly Perl, but it's been a while that I want to be less lazy and code with Python, so it's a good opportunity.

**Comment by vinitkumar** [comment]
@gevrey Will send you a mail and let's take it up from there. 
@ics-brettma There are a lot of areas you can contribute to. You can help with the documentation as well and sure as well pick up small issues on the project. They would be quite easy to deal with and reading code is a good way to master a language.

**Comment by vinitkumar** [comment]
@gevrey I tried sending the mail to gevery@pobox.com but the mail delivery was failed. Is the address correct if not please give me the correct one.

**Comment by orjanv** [comment]
Hi, just came across this thread, anything new on this end?

**Comment by ildar** [comment]
Nope, noone to work on it.

**Comment by orjanv** [comment]
Thanks for the quick response. I needed only parts of the googlecl tool, the ability to blog from command line to blogger. I wrote a tiny script to do this, similarly as the googlecl command did: [](https://github.com/orjanv/early-galaxy)

Be aware that this was written quickly and there might be lots of bugs and pits in the code. If you find this useful, I'm glad. :) I also appreciate suggestions and code contributions.

**Comment by ildar** [comment]
Can you show it if it works?

**Comment by vinitkumar** [comment]
@ildar I have started on oauth2 and should be able to restore some of the functionality back. Will post on this thread once I have something stable.

**Comment by ildar** [comment]
@vinitkumar , thanks!

**Comment by orjanv** [comment]
The example in my script is: `python blogger.py --title "Five nice haiku poems" --labels "haiku" --src haiku.html ` which runs fine after the authentication is done using a browser.

**Comment by huangzonghao** [comment]
thanks dude, really looking forward to that!

**Comment by mattburman** [comment]
Any recent progress on this?

**Comment by jeisner** [comment]
Just a reminder that some of us are handicapped without our googlecl and would love to have it back!

For example, I have a script that uses Google Docs to export Microsoft Office files to PDF, even though I'm using Linux and don't have Office.  The reason is that Google Docs renders layout (e.g. Powerpoint) quite faithfully, unlike LibreOffice.  It was great while googlecl worked!

**Comment by Konstantinusz** [comment]
Try out this similar CLI app https://github.com/tokland/shoogle

**Comment by badboy** [comment]
@jeisner Just as a reminder: This is open source. If it does not work for you, don't demand someone fixing it for you. Jump in and help or look for alternatives. There are very good reasons for people not working on this, don't put the burden on them.

**Comment by vinitkumar** [comment]
@jeisner @Konstantinusz @badboy I have recently regained work on refactoring the authentication part. It is going good but gdata (the library to talk to google services) has major breaking changes and I need to change some api interaction part. This is a major refactor and will take some time. Though, I have decided to port it one by one. I am planning to first upgrade the google docs part so that googlecl partially works and with time and support for community hopefully we will get it fully functional.

**Comment by badboy** [comment]
@vinitkumar I appreciate your effort!

**Comment by jeisner** [comment]
@vinitkumar Thanks so much!  Sorry to hear that gdata has changed so drastically.  My previous message was meant to sound like cheerleading, not entitlement, so I hope you weren't offended by it - I'm of course very grateful for all of the open-source software I use.

**Comment by vinitkumar** [comment]
@jeisner Nope. Not at all offended. I am myself an user of googlecl so I want it to work soon as much as any one else. Sadly I had a very busy work life so couldn't find much time for open source past months. Hopefully very soon I will be able to post atleast alpha version of updated code and get some feedback. I will keep this issue open and post updates here.

**Comment by vinitkumar** [comment]
Work in progress: https://github.com/vinitkumar/googlecl/pull/258#issue-144469748

**Comment by vinitkumar** [comment]
New Issue to track the issues here and by attempting a rewrite #274. Closing this in favour of that ticket.
