### ISSUE TITLE
No module named gdata.photos.service

### ISSUE THREAD

**Issue by gevrey** [vinitkumar/googlecl#263]
cri@wscg8:~/dev/googlecl$ python src/google.py picasa list --title=vinit
Traceback (most recent call last):
  File "src/google.py", line 56, in <module>
    import googlecl.authenticate
  File "/home/cri/dev/googlecl/src/googlecl/authenticate.py", line 5, in <module>
    from gdata.photos.service import PhotosService
ImportError: No module named gdata.photos.service

**Comment by vinitkumar** [comment]
Please run `python setup.py install` first and then run the command.

**Comment by gevrey** [comment]
That worked! Thanks.

What are the Google services supported as of today? (anyhow, Photos are the most important to me, so thanks a ton for making it work!)

**Comment by vinitkumar** [comment]
The support for other services is limited. I haven't got time, yet. But I hope to hack more on it in near future.
