### ISSUE TITLE
Can't list contacts

### ISSUE THREAD

**Issue by wjhendr** [vinitkumar/googlecl#265]
Hello,

I just cloned (version `0.9.15`) and installed.  When prompted at first run, I entered:

    Please specify user: *********@gmail.com
    Please specify title: contacts

I then got my auth code from a browser, pasted it in, and it got accepted:

    Successfully retrieved access token

I cannot list contacts, though:

    google contacts list

The above command gives the error:

    AttributeError: 'ContactsService' object has no attribute 'GetContacts'

What is the problem?  Probably something I'm doing/not doing, but googling and searching here yielded nothing.

Thanks

**Comment by vinitkumar** [comment]
@wjhendr thanks for reporting this issue. The underlying library has been upgraded but not all code is updated in this tool. It's a problem at our end. I will try to fix this. Please look out for this issue, when done, I will put the update here.

**Comment by vinitkumar** [comment]
Note to self: https://gist.github.com/jay0lee/2bfa451e1f79354f450ff5f1a757e743

**Comment by karlguy** [comment]
Similar problems here:
```
~/download/googlecl master 
❯ python2 src/google.py docs list

Refreshing access_token
Traceback (most recent call last):
  File "src/google.py", line 956, in <module>
    main()
  File "src/google.py", line 942, in main
    run_once(options, args)
  File "src/google.py", line 735, in run_once
    raise run_error
AttributeError: 'DocsService' object has no attribute 'get_folder'
```

**Comment by vinitkumar** [comment]
@wjhendr Bug from my side to get the oauth2 getting to work somehow. The new rewrite will resolve this. Keep an eye on #274.
