### ISSUE TITLE
Google Takeout

### ISSUE THREAD

**Issue by maciekish** [vinitkumar/googlecl#267]
Is there support for this? I need to regularly download my location history as json for geotagging.

**Comment by vinitkumar** [comment]
Not yet. But I will be doing a development sprint. I can look into the possibility of adding this. Will update this ticket once done.

**Comment by maciekish** [comment]
Great, thanks!

**Comment by vinitkumar** [comment]
@maciekish Will look into the possibility of adding this in the rewritten version of this library. Keep a look into #274 for this.
