### ISSUE TITLE
Is Calendar working?

### ISSUE THREAD

**Issue by jtgd** [vinitkumar/googlecl#271]
It's been a while since I installed, and I see frequent updates, but I've never seen calendar work (the only part I want to use). I get this odd error message:

    $ google calendar help
    No module named calendar
    Did you specify the service correctly? Must be one of 'help', 'picasa', 'blogger', 'youtube', 'docs', 'contacts', 'calendar', 'finance'

which is simultaneously telling me that there is no calendar module and that there is.

Am I doing something wrong? Does it work for others? Or is this just broken at the moment?  If it's a WIP I'll be patient.

**Comment by vinitkumar** [comment]
@jtgd You are not doing anything wrong. The `gdata` apis supporting this were deprecated and I got really busy and didn't had time to maintain it. I am attempting a rewrite and that will fix a lot of the issues you face now.  Closing this in favour of #274
