### ISSUE TITLE
Failed to get valid access token. 

### ISSUE THREAD

**Issue by ritobanrc** [vinitkumar/googlecl#272]
I have just installed this from the AUR, and none of the commands appear to work at all. I'm not getting a password prompt, etc. Here is the terminal output: 
```
$ google docs edit
Please specify user: ritobanrc@gmail.com
Please specify title: Python Data
Unable to obtain OAuth request token: 307, <HTML>


<HEAD>
<TITLE>Temporary Redirect</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Temporary Redirect</H1>
The document has moved <A `HREF="https://accounts.google.com/OAuthGetRequestToken?scope=https%3A%2F%2Fdocs.google.com%2Ffeeds%2F+https%3A%2F%2Fspreadsheets.google.com%2Ffeeds%2F+https%3A%2F%2Fdocs.googleusercontent.com%2F+https%3A%2F%2Fspreadsheets.google.com%2Ffeeds%2F+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo%23email&amp;xoauth_displayname=GoogleCL+ritoban%40ritoban-manjaro">here</A>.`
</BODY>
</HTML>

Failed to get valid access token!
```

**Comment by vinitkumar** [comment]
@ritobanrc The project has not been maintained for couple of years now as I am not able to find time for it. Also, google has changed a lot of things and the Oath has changed. I can't promise anything at this point but once I find time & fix these issue,  I will post an update here as well.

**Comment by vinitkumar** [comment]
@ritobanrc Keep a close eye of #274. Attempting a rewrite and hoping a lot of these issues are solved by it.
